# Generated by Django 4.2.3 on 2023-07-12 21:50

import class_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0006_alter_student_locker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, validators=[class_app.validators.validate_subject_format])),
                ('professor', models.CharField(default='Mr. Cahan', max_length=255, validators=[class_app.validators.validate_professor_name])),
                ('students', models.ManyToManyField(to='student_app.student')),
            ],
        ),
    ]
