# Generated by Django 4.2.3 on 2023-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_student_locker_number'),
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='student_app.student'),
        ),
    ]
