# Generated by Django 4.2.3 on 2023-07-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_alter_class_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
